# Generated by Django 3.2.9 on 2021-11-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20211129_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video',
            new_name='video_id',
        ),
    ]
